
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 12 14:35:56 EDT 2018
//----------------------------------------------------

package com.imsweb.validation.translation.language;

/** CUP generated class containing symbol constants. */
public class GeneditsTokenType {
  /* terminals */
  public static final int RBRACK = 12;
  public static final int SEMICOLON = 16;
  public static final int ELSE = 3;
  public static final int RBRACE = 10;
  public static final int RPAREN = 8;
  public static final int WHILE = 4;
  public static final int CONSTANT = 25;
  public static final int MINUS_OP = 22;
  public static final int LBRACK = 11;
  public static final int IDENTIFIER = 26;
  public static final int RETURN = 5;
  public static final int SPOUND = 14;
  public static final int FUNCTION = 6;
  public static final int IF = 2;
  public static final int LPAREN = 7;
  public static final int LBRACE = 9;
  public static final int LPOUND = 15;
  public static final int TYPE = 27;
  public static final int STRING = 24;
  public static final int EMPTY_LINE = 18;
  public static final int COMMA = 17;
  public static final int BINARY_OP = 20;
  public static final int NUMBER = 23;
  public static final int EOF = 0;
  public static final int COMMENT = 28;
  public static final int ARITHMETHIC_OP = 19;
  public static final int error = 1;
  public static final int UNARY_OP = 21;
  public static final int EQ = 13;
}

