
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 04 10:20:20 EDT 2026
//----------------------------------------------------

package com.imsweb.validation.translation.language;

/** CUP generated class containing symbol constants. */
public class GeneditsTokenType {
  /* terminals */
  public static final int RBRACK = 13;
  public static final int SEMICOLON = 17;
  public static final int ELSE = 4;
  public static final int RBRACE = 11;
  public static final int RPAREN = 9;
  public static final int WHILE = 5;
  public static final int CONSTANT = 26;
  public static final int MINUS_OP = 23;
  public static final int LBRACK = 12;
  public static final int IDENTIFIER = 27;
  public static final int RETURN = 6;
  public static final int SPOUND = 15;
  public static final int FUNCTION = 7;
  public static final int IF = 2;
  public static final int LPAREN = 8;
  public static final int LBRACE = 10;
  public static final int LPOUND = 16;
  public static final int TYPE = 28;
  public static final int STRING = 25;
  public static final int EMPTY_LINE = 19;
  public static final int COMMA = 18;
  public static final int BINARY_OP = 21;
  public static final int NUMBER = 24;
  public static final int EOF = 0;
  public static final int COMMENT = 29;
  public static final int ARITHMETHIC_OP = 20;
  public static final int error = 1;
  public static final int UNARY_OP = 22;
  public static final int EQ = 14;
  public static final int FOR = 3;
}

