
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 04 10:20:21 EDT 2026
//----------------------------------------------------

package com.imsweb.validation.translation.language;

import com.imsweb.validation.translation.language.entity.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sat Apr 04 10:20:21 EDT 2026
  */
public class GeneditsParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public GeneditsParser() {super();}

  /** Constructor which sets the default scanner. */
  public GeneditsParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public GeneditsParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\064\000\002\002\004\000\002\002\003\000\002\003" +
    "\005\000\002\003\005\000\002\004\004\000\002\004\004" +
    "\000\002\004\004\000\002\004\003\000\002\005\006\000" +
    "\002\006\002\000\002\006\004\000\002\007\004\000\002" +
    "\007\006\000\002\007\007\000\002\007\006\000\002\007" +
    "\010\000\002\007\011\000\002\007\007\000\002\007\007" +
    "\000\002\007\017\000\002\007\007\000\002\021\002\000" +
    "\002\021\003\000\002\010\003\000\002\010\003\000\002" +
    "\011\003\000\002\011\003\000\002\012\003\000\002\012" +
    "\003\000\002\012\003\000\002\012\003\000\002\012\003" +
    "\000\002\012\003\000\002\012\004\000\002\012\004\000" +
    "\002\012\006\000\002\012\006\000\002\012\006\000\002" +
    "\012\004\000\002\012\004\000\002\012\006\000\002\012" +
    "\006\000\002\013\004\000\002\014\005\000\002\020\003" +
    "\000\002\020\005\000\002\017\006\000\002\017\003\000" +
    "\002\015\002\000\002\015\003\000\002\016\003\000\002" +
    "\016\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\171\000\030\004\014\005\025\007\007\010\010\011" +
    "\012\014\015\023\004\025\020\035\011\036\017\037\023" +
    "\001\002\000\036\002\uffec\004\uffec\005\uffec\006\uffec\007" +
    "\uffec\010\uffec\011\uffec\014\uffec\015\uffec\023\uffec\025\uffec" +
    "\035\uffec\036\uffec\037\127\001\002\000\034\002\uffe8\004" +
    "\uffe8\005\uffe8\007\uffe8\010\uffe8\011\uffe8\014\uffe8\015\uffe8" +
    "\023\uffe8\025\uffe8\035\uffe8\036\uffe8\037\uffe8\001\002\000" +
    "\004\002\000\001\002\000\004\012\167\001\002\000\026" +
    "\012\046\021\037\022\034\030\040\031\035\032\036\033" +
    "\041\034\032\035\044\037\045\001\002\000\010\012\157" +
    "\016\120\020\uffd2\001\002\000\004\035\153\001\002\000" +
    "\034\002\ufffa\004\014\005\025\007\007\010\010\011\012" +
    "\014\015\015\ufffa\023\004\025\020\035\011\036\017\037" +
    "\023\001\002\000\004\012\143\001\002\000\030\004\014" +
    "\005\025\007\007\010\010\011\012\014\015\023\004\025" +
    "\020\035\011\036\017\037\023\001\002\000\026\004\014" +
    "\005\025\007\007\010\010\011\012\023\004\025\020\035" +
    "\011\036\017\037\023\001\002\000\004\035\027\001\002" +
    "\000\056\002\uffea\004\uffea\005\uffea\006\uffea\007\uffea\010" +
    "\uffea\011\uffea\012\uffea\014\uffea\015\uffea\021\uffea\022\uffea" +
    "\023\uffea\025\uffea\030\uffea\031\uffea\032\uffea\033\uffea\034" +
    "\uffea\035\uffea\036\uffea\037\uffea\001\002\000\004\020\124" +
    "\001\002\000\034\002\uffe7\004\uffe7\005\uffe7\007\uffe7\010" +
    "\uffe7\011\uffe7\014\uffe7\015\uffe7\023\uffe7\025\uffe7\035\uffe7" +
    "\036\uffe7\037\uffe7\001\002\000\056\002\uffe9\004\uffe9\005" +
    "\uffe9\006\uffe9\007\uffe9\010\uffe9\011\uffe9\012\uffe9\014\uffe9" +
    "\015\uffe9\021\uffe9\022\uffe9\023\uffe9\025\uffe9\030\uffe9\031" +
    "\uffe9\032\uffe9\033\uffe9\034\uffe9\035\uffe9\036\uffe9\037\uffe9" +
    "\001\002\000\004\002\123\001\002\000\004\012\026\001" +
    "\002\000\004\035\027\001\002\000\012\016\120\020\uffd2" +
    "\023\uffd2\024\uffd2\001\002\000\004\020\031\001\002\000" +
    "\026\012\046\021\037\022\034\030\040\031\035\032\036" +
    "\033\041\034\032\035\044\037\045\001\002\000\020\012" +
    "\115\013\uffe4\023\uffe4\024\uffe4\026\uffe4\027\uffe4\031\uffe4" +
    "\001\002\000\016\013\uffe5\023\uffe5\024\uffe5\026\uffe5\027" +
    "\uffe5\031\uffe5\001\002\000\004\033\114\001\002\000\026" +
    "\012\046\021\037\022\034\030\040\031\035\032\036\033" +
    "\041\034\032\035\044\037\045\001\002\000\016\013\uffe2" +
    "\023\uffe2\024\uffe2\026\uffe2\027\uffe2\031\uffe2\001\002\000" +
    "\004\033\112\001\002\000\026\012\046\021\037\022\034" +
    "\030\040\031\035\032\036\033\041\034\032\035\044\037" +
    "\045\001\002\000\016\013\uffe3\023\uffe3\024\uffe3\026\uffe3" +
    "\027\uffe3\031\uffe3\001\002\000\012\023\074\026\052\027" +
    "\053\031\051\001\002\000\016\013\uffe6\023\uffe6\024\uffe6" +
    "\026\uffe6\027\uffe6\031\uffe6\001\002\000\020\012\065\013" +
    "\uffe1\023\uffe1\024\uffe1\026\uffe1\027\uffe1\031\uffe1\001\002" +
    "\000\026\012\046\021\037\022\034\030\040\031\035\032" +
    "\036\033\041\034\032\035\044\037\045\001\002\000\026" +
    "\012\046\021\037\022\034\030\040\031\035\032\036\033" +
    "\041\034\032\035\044\037\045\001\002\000\012\013\050" +
    "\026\052\027\053\031\051\001\002\000\016\013\uffd6\023" +
    "\uffd6\024\uffd6\026\uffd6\027\uffd6\031\uffd6\001\002\000\030" +
    "\012\ufff8\021\ufff8\022\ufff8\025\020\030\ufff8\031\ufff8\032" +
    "\ufff8\033\ufff8\034\ufff8\035\ufff8\037\023\001\002\000\030" +
    "\012\ufff8\021\ufff8\022\ufff8\025\020\030\ufff8\031\ufff8\032" +
    "\ufff8\033\ufff8\034\ufff8\035\ufff8\037\023\001\002\000\030" +
    "\012\ufff8\021\ufff8\022\ufff8\025\020\030\ufff8\031\ufff8\032" +
    "\ufff8\033\ufff8\034\ufff8\035\ufff8\037\023\001\002\000\026" +
    "\012\046\021\037\022\034\030\040\031\035\032\036\033" +
    "\041\034\032\035\044\037\045\001\002\000\056\002\ufff8" +
    "\004\ufff8\005\ufff8\006\ufff8\007\ufff8\010\ufff8\011\ufff8\012" +
    "\ufff8\014\ufff8\015\ufff8\021\ufff8\022\ufff8\023\ufff8\025\020" +
    "\030\ufff8\031\ufff8\032\ufff8\033\ufff8\034\ufff8\035\ufff8\036" +
    "\ufff8\037\023\001\002\000\056\002\ufff7\004\ufff7\005\ufff7" +
    "\006\ufff7\007\ufff7\010\ufff7\011\ufff7\012\ufff7\014\ufff7\015" +
    "\ufff7\021\ufff7\022\ufff7\023\ufff7\025\ufff7\030\ufff7\031\ufff7" +
    "\032\ufff7\033\ufff7\034\ufff7\035\ufff7\036\ufff7\037\ufff7\001" +
    "\002\000\016\013\uffdd\023\uffdd\024\uffdd\026\uffdd\027\uffdd" +
    "\031\uffdd\001\002\000\026\012\046\021\037\022\034\030" +
    "\040\031\035\032\036\033\041\034\032\035\044\037\045" +
    "\001\002\000\016\013\uffde\023\uffde\024\uffde\026\uffde\027" +
    "\uffde\031\uffde\001\002\000\026\012\046\021\037\022\034" +
    "\030\040\031\035\032\036\033\041\034\032\035\044\037" +
    "\045\001\002\000\016\013\uffdc\023\uffdc\024\uffdc\026\uffdc" +
    "\027\uffdc\031\uffdc\001\002\000\016\013\uffd7\023\uffd7\024" +
    "\uffd7\026\uffd7\027\uffd7\031\uffd7\001\002\000\030\012\046" +
    "\013\uffd1\021\037\022\034\030\040\031\035\032\036\033" +
    "\041\034\032\035\044\037\045\001\002\000\004\013\073" +
    "\001\002\000\006\013\uffd0\024\071\001\002\000\014\013" +
    "\uffcf\024\uffcf\026\052\027\053\031\051\001\002\000\026" +
    "\012\046\021\037\022\034\030\040\031\035\032\036\033" +
    "\041\034\032\035\044\037\045\001\002\000\014\013\uffce" +
    "\024\uffce\026\052\027\053\031\051\001\002\000\016\013" +
    "\uffd9\023\uffd9\024\uffd9\026\uffd9\027\uffd9\031\uffd9\001\002" +
    "\000\026\012\046\021\037\022\034\030\040\031\035\032" +
    "\036\033\041\034\032\035\044\037\045\001\002\000\012" +
    "\023\076\026\052\027\053\031\051\001\002\000\004\035" +
    "\027\001\002\000\004\020\100\001\002\000\026\012\046" +
    "\021\037\022\034\030\040\031\035\032\036\033\041\034" +
    "\032\035\044\037\045\001\002\000\012\013\102\026\052" +
    "\027\053\031\051\001\002\000\030\004\ufff8\005\ufff8\007" +
    "\ufff8\010\ufff8\011\ufff8\014\ufff8\023\ufff8\025\020\035\ufff8" +
    "\036\ufff8\037\023\001\002\000\036\002\uffee\004\uffee\005" +
    "\uffee\006\uffee\007\uffee\010\uffee\011\uffee\014\uffee\015\uffee" +
    "\023\uffee\025\uffee\035\uffee\036\uffee\037\uffee\001\002\000" +
    "\024\004\014\005\025\007\007\010\010\011\012\014\015" +
    "\023\004\035\011\036\017\001\002\000\036\002\ufff8\004" +
    "\ufff8\005\ufff8\006\ufff8\007\ufff8\010\ufff8\011\ufff8\014\ufff8" +
    "\015\ufff8\023\ufff8\025\020\035\ufff8\036\ufff8\037\023\001" +
    "\002\000\036\002\ufff8\004\ufff8\005\ufff8\006\ufff8\007\ufff8" +
    "\010\ufff8\011\ufff8\014\ufff8\015\ufff8\023\ufff8\025\020\035" +
    "\ufff8\036\ufff8\037\023\001\002\000\036\002\ufffe\004\ufffe" +
    "\005\ufffe\006\ufffe\007\ufffe\010\ufffe\011\ufffe\014\ufffe\015" +
    "\ufffe\023\ufffe\025\ufffe\035\ufffe\036\ufffe\037\ufffe\001\002" +
    "\000\036\002\uffff\004\uffff\005\uffff\006\uffff\007\uffff\010" +
    "\uffff\011\uffff\014\uffff\015\uffff\023\uffff\025\uffff\035\uffff" +
    "\036\uffff\037\uffff\001\002\000\016\013\uffdb\023\uffdb\024" +
    "\uffdb\026\052\027\053\031\051\001\002\000\016\013\uffe0" +
    "\023\uffe0\024\uffe0\026\uffe0\027\uffe0\031\uffe0\001\002\000" +
    "\016\013\uffda\023\uffda\024\uffda\026\uffda\027\uffda\031\uffda" +
    "\001\002\000\016\013\uffdf\023\uffdf\024\uffdf\026\uffdf\027" +
    "\uffdf\031\uffdf\001\002\000\030\012\046\013\uffd1\021\037" +
    "\022\034\030\040\031\035\032\036\033\041\034\032\035" +
    "\044\037\045\001\002\000\004\013\117\001\002\000\016" +
    "\013\uffd8\023\uffd8\024\uffd8\026\uffd8\027\uffd8\031\uffd8\001" +
    "\002\000\004\032\121\001\002\000\004\017\122\001\002" +
    "\000\010\020\uffd3\023\uffd3\024\uffd3\001\002\000\004\002" +
    "\001\001\002\000\026\012\046\021\037\022\034\030\040" +
    "\031\035\032\036\033\041\034\032\035\044\037\045\001" +
    "\002\000\012\023\126\026\052\027\053\031\051\001\002" +
    "\000\036\002\uffec\004\uffec\005\uffec\006\uffec\007\uffec\010" +
    "\uffec\011\uffec\014\uffec\015\uffec\023\uffec\025\uffec\035\uffec" +
    "\036\uffec\037\127\001\002\000\036\002\uffeb\004\uffeb\005" +
    "\uffeb\006\uffeb\007\uffeb\010\uffeb\011\uffeb\014\uffeb\015\uffeb" +
    "\023\uffeb\025\uffeb\035\uffeb\036\uffeb\037\uffeb\001\002\000" +
    "\036\002\ufff4\004\ufff4\005\ufff4\006\ufff4\007\ufff4\010\ufff4" +
    "\011\ufff4\014\ufff4\015\ufff4\023\ufff4\025\ufff4\035\ufff4\036" +
    "\ufff4\037\ufff4\001\002\000\004\023\135\001\002\000\006" +
    "\023\uffd5\024\133\001\002\000\004\035\027\001\002\000" +
    "\004\023\uffd4\001\002\000\036\002\uffec\004\uffec\005\uffec" +
    "\006\uffec\007\uffec\010\uffec\011\uffec\014\uffec\015\uffec\023" +
    "\uffec\025\uffec\035\uffec\036\uffec\037\127\001\002\000\036" +
    "\002\ufff5\004\ufff5\005\ufff5\006\ufff5\007\ufff5\010\ufff5\011" +
    "\ufff5\014\ufff5\015\ufff5\023\ufff5\025\ufff5\035\ufff5\036\ufff5" +
    "\037\ufff5\001\002\000\006\002\ufffb\015\ufffb\001\002\000" +
    "\004\015\141\001\002\000\036\002\ufff8\004\ufff8\005\ufff8" +
    "\006\ufff8\007\ufff8\010\ufff8\011\ufff8\014\ufff8\015\ufff8\023" +
    "\ufff8\025\020\035\ufff8\036\ufff8\037\023\001\002\000\036" +
    "\002\ufff9\004\ufff9\005\ufff9\006\ufff9\007\ufff9\010\ufff9\011" +
    "\ufff9\014\ufff9\015\ufff9\023\ufff9\025\ufff9\035\ufff9\036\ufff9" +
    "\037\ufff9\001\002\000\026\012\046\021\037\022\034\030" +
    "\040\031\035\032\036\033\041\034\032\035\044\037\045" +
    "\001\002\000\012\013\145\026\052\027\053\031\051\001" +
    "\002\000\030\004\ufff8\005\ufff8\007\ufff8\010\ufff8\011\ufff8" +
    "\014\ufff8\023\ufff8\025\020\035\ufff8\036\ufff8\037\023\001" +
    "\002\000\036\002\ufff0\004\ufff0\005\ufff0\006\147\007\ufff0" +
    "\010\ufff0\011\ufff0\014\ufff0\015\ufff0\023\ufff0\025\ufff0\035" +
    "\ufff0\036\ufff0\037\ufff0\001\002\000\030\004\ufff8\005\ufff8" +
    "\007\ufff8\010\ufff8\011\ufff8\014\ufff8\023\ufff8\025\020\035" +
    "\ufff8\036\ufff8\037\023\001\002\000\036\002\ufff1\004\ufff1" +
    "\005\ufff1\006\ufff1\007\ufff1\010\ufff1\011\ufff1\014\ufff1\015" +
    "\ufff1\023\ufff1\025\ufff1\035\ufff1\036\ufff1\037\ufff1\001\002" +
    "\000\006\002\ufffd\015\ufffd\001\002\000\032\002\ufffc\004" +
    "\014\005\025\007\007\010\010\011\012\015\ufffc\023\004" +
    "\025\020\035\011\036\017\037\023\001\002\000\004\012" +
    "\154\001\002\000\004\013\155\001\002\000\030\004\ufff8" +
    "\005\ufff8\007\ufff8\010\ufff8\011\ufff8\014\ufff8\023\ufff8\025" +
    "\020\035\ufff8\036\ufff8\037\023\001\002\000\036\002\uffed" +
    "\004\uffed\005\uffed\006\uffed\007\uffed\010\uffed\011\uffed\014" +
    "\uffed\015\uffed\023\uffed\025\uffed\035\uffed\036\uffed\037\uffed" +
    "\001\002\000\030\012\046\013\uffd1\021\037\022\034\030" +
    "\040\031\035\032\036\033\041\034\032\035\044\037\045" +
    "\001\002\000\004\013\161\001\002\000\004\023\162\001" +
    "\002\000\036\002\uffec\004\uffec\005\uffec\006\uffec\007\uffec" +
    "\010\uffec\011\uffec\014\uffec\015\uffec\023\uffec\025\uffec\035" +
    "\uffec\036\uffec\037\127\001\002\000\036\002\ufff2\004\ufff2" +
    "\005\ufff2\006\ufff2\007\ufff2\010\ufff2\011\ufff2\014\ufff2\015" +
    "\ufff2\023\ufff2\025\ufff2\035\ufff2\036\ufff2\037\ufff2\001\002" +
    "\000\012\023\165\026\052\027\053\031\051\001\002\000" +
    "\036\002\uffec\004\uffec\005\uffec\006\uffec\007\uffec\010\uffec" +
    "\011\uffec\014\uffec\015\uffec\023\uffec\025\uffec\035\uffec\036" +
    "\uffec\037\127\001\002\000\036\002\ufff3\004\ufff3\005\ufff3" +
    "\006\ufff3\007\ufff3\010\ufff3\011\ufff3\014\ufff3\015\ufff3\023" +
    "\ufff3\025\ufff3\035\ufff3\036\ufff3\037\ufff3\001\002\000\026" +
    "\012\046\021\037\022\034\030\040\031\035\032\036\033" +
    "\041\034\032\035\044\037\045\001\002\000\012\013\171" +
    "\026\052\027\053\031\051\001\002\000\030\004\ufff8\005" +
    "\ufff8\007\ufff8\010\ufff8\011\ufff8\014\ufff8\023\ufff8\025\020" +
    "\035\ufff8\036\ufff8\037\023\001\002\000\036\002\uffef\004" +
    "\uffef\005\uffef\006\uffef\007\uffef\010\uffef\011\uffef\014\uffef" +
    "\015\uffef\023\uffef\025\uffef\035\uffef\036\uffef\037\uffef\001" +
    "\002\000\036\002\ufff6\004\ufff6\005\ufff6\006\ufff6\007\ufff6" +
    "\010\ufff6\011\ufff6\014\ufff6\015\ufff6\023\ufff6\025\ufff6\035" +
    "\ufff6\036\ufff6\037\ufff6\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\171\000\020\002\023\004\005\005\015\007\004\010" +
    "\021\011\012\017\020\001\001\000\004\021\172\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\012\163\013\032\014\042\001\001\000\002\001\001" +
    "\000\002\001\001\000\016\004\150\005\151\007\004\010" +
    "\021\011\012\017\020\001\001\000\002\001\001\000\016" +
    "\004\137\005\015\007\004\010\021\011\012\017\020\001" +
    "\001\000\012\007\004\010\021\011\136\017\020\001\001" +
    "\000\006\017\131\020\130\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\017\027\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\012\041\013\032" +
    "\014\042\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\012\112\013\032\014\042\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\012\110\013" +
    "\032\014\042\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\012\063\013" +
    "\032\014\042\001\001\000\010\012\046\013\032\014\042" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\006" +
    "\061\010\054\001\001\000\006\006\057\010\054\001\001" +
    "\000\006\006\053\010\054\001\001\000\010\012\056\013" +
    "\032\014\042\001\001\000\006\006\055\010\054\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\012\060\013" +
    "\032\014\042\001\001\000\002\001\001\000\010\012\062" +
    "\013\032\014\042\001\001\000\002\001\001\000\002\001" +
    "\001\000\014\012\067\013\032\014\042\015\065\016\066" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\012\071\013\032\014\042\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\012\074\013\032\014" +
    "\042\001\001\000\002\001\001\000\004\017\076\001\001" +
    "\000\002\001\001\000\010\012\100\013\032\014\042\001" +
    "\001\000\002\001\001\000\010\003\102\006\103\010\054" +
    "\001\001\000\002\001\001\000\010\005\104\007\105\017" +
    "\020\001\001\000\006\006\107\010\054\001\001\000\006" +
    "\006\106\010\054\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\014\012\067\013\032\014\042\015" +
    "\115\016\066\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\012\124\013\032\014\042\001\001" +
    "\000\002\001\001\000\004\021\127\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\017\131\020\133\001\001\000\002\001\001\000" +
    "\004\021\135\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\006\141\010\054\001\001\000" +
    "\002\001\001\000\010\012\143\013\032\014\042\001\001" +
    "\000\002\001\001\000\010\003\145\006\103\010\054\001" +
    "\001\000\002\001\001\000\010\003\147\006\103\010\054" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\007" +
    "\004\010\021\011\136\017\020\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\003\155\006\103\010\054\001" +
    "\001\000\002\001\001\000\014\012\067\013\032\014\042" +
    "\015\157\016\066\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\021\162\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\021\165\001\001\000\002\001\001\000" +
    "\010\012\167\013\032\014\042\001\001\000\002\001\001" +
    "\000\010\003\171\006\103\010\054\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$GeneditsParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$GeneditsParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$GeneditsParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    public void report_error(String message, Object info) {
        StringBuilder m = new StringBuilder("Error");
        if (info instanceof java_cup.runtime.Symbol) {
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
            if (s.left >= 0) {                
                m.append(" in line "+(s.left+1));   
                if (s.right >= 0)                    
                    m.append(", column "+(s.right+1));
            }
        }
        m.append(" : " + message);
    }

    public void report_fatal_error(String message, Object info) {
        StringBuilder m = new StringBuilder("Error");
        if (info instanceof java_cup.runtime.Symbol) {
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
            if (s.left >= 0) {                
                m.append(" in line "+(s.left+1));   
                if (s.right >= 0)                    
                    m.append(", column "+(s.right+1));
            }
        }
        m.append(" : " + message);
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$GeneditsParser$actions {
  private final GeneditsParser parser;

  /** Constructor */
  CUP$GeneditsParser$actions(GeneditsParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$GeneditsParser$do_action(
    int                        CUP$GeneditsParser$act_num,
    java_cup.runtime.lr_parser CUP$GeneditsParser$parser,
    java.util.Stack            CUP$GeneditsParser$stack,
    int                        CUP$GeneditsParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$GeneditsParser$result;

      /* select the action based on the action number */
      switch (CUP$GeneditsParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // argument_list ::= argument_list COMMA expression 
            {
              ArgumentList RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).right;
		ArgumentList a = (ArgumentList)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new ArgumentList(a, e); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("argument_list",12, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // argument_list ::= expression 
            {
              ArgumentList RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new ArgumentList(e); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("argument_list",12, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // argument_list_opt ::= argument_list 
            {
              ArgumentList RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		ArgumentList a = (ArgumentList)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new ArgumentList(a); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("argument_list_opt",11, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // argument_list_opt ::= 
            {
              ArgumentList RESULT =null;
		 RESULT = new ArgumentList(); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("argument_list_opt",11, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // variable_declaration ::= IDENTIFIER 
            {
              VariableDeclaration RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		java.lang.String i = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new VariableDeclaration(i); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("variable_declaration",13, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // variable_declaration ::= IDENTIFIER LBRACK NUMBER RBRACK 
            {
              VariableDeclaration RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).right;
		java.lang.String i = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).right;
		java.lang.Integer n = (java.lang.Integer)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).value;
		 RESULT = new VariableDeclaration(i, n); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("variable_declaration",13, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // variable_declaration_list ::= variable_declaration COMMA variable_declaration_list 
            {
              java.util.List RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).right;
		VariableDeclaration v = (VariableDeclaration)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		java.util.List l = (java.util.List)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new java.util.ArrayList(); RESULT.add(v); RESULT.addAll(l); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("variable_declaration_list",14, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // variable_declaration_list ::= variable_declaration 
            {
              java.util.List RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		VariableDeclaration v = (VariableDeclaration)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new java.util.ArrayList(); RESULT.add(v); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("variable_declaration_list",14, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expression_with_parenthesis ::= LPAREN expression RPAREN 
            {
              ExpressionWithParenthesis RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).value;
		 RESULT = new ExpressionWithParenthesis(e); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("expression_with_parenthesis",10, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expression_with_comment ::= COMMENT expression 
            {
              Expression RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).right;
		java.lang.String c = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = e; 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("expression_with_comment",9, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expression ::= CONSTANT LPAREN argument_list_opt RPAREN 
            {
              Expression RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).right;
		java.lang.String i = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).right;
		ArgumentList a = (ArgumentList)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).value;
		 RESULT = new MethodInvocationExpression(i, a); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("expression",8, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expression ::= IDENTIFIER LPAREN argument_list_opt RPAREN 
            {
              Expression RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).right;
		java.lang.String i = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).right;
		ArgumentList a = (ArgumentList)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).value;
		 RESULT = new MethodInvocationExpression(i, a); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("expression",8, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expression ::= MINUS_OP expression 
            {
              Expression RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).right;
		java.lang.String o = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new OperationExpression(e, o); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("expression",8, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expression ::= UNARY_OP expression 
            {
              Expression RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).right;
		java.lang.String o = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new OperationExpression(e, o); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("expression",8, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expression ::= expression MINUS_OP empty_statements_opt expression 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).right;
		java.lang.String o = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new OperationExpression(e1, e2, o); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("expression",8, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expression ::= expression BINARY_OP empty_statements_opt expression 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).right;
		java.lang.String o = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new OperationExpression(e1, e2, o); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("expression",8, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expression ::= expression ARITHMETHIC_OP empty_statements_opt expression 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).right;
		java.lang.String o = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new OperationExpression(e1, e2, o); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("expression",8, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expression ::= LPOUND STRING 
            {
              Expression RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		java.lang.String s = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new FieldExpression(s.substring(1, s.length() - 1), false); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("expression",8, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expression ::= SPOUND STRING 
            {
              Expression RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		java.lang.String s = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new FieldExpression(s.substring(1, s.length() - 1), true); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("expression",8, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expression ::= IDENTIFIER 
            {
              Expression RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		java.lang.String i = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new LiteralExpression(i); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("expression",8, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expression ::= NUMBER 
            {
              Expression RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		java.lang.Integer n = (java.lang.Integer)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new LiteralExpression(String.valueOf(n)); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("expression",8, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expression ::= STRING 
            {
              Expression RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		java.lang.String s = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new LiteralExpression(s.replaceAll("\r?\n", "")); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("expression",8, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expression ::= CONSTANT 
            {
              Expression RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		java.lang.String c = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new ConstantExpression(c); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("expression",8, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expression ::= expression_with_comment 
            {
              Expression RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = e; 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("expression",8, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expression ::= expression_with_parenthesis 
            {
              Expression RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		ExpressionWithParenthesis e = (ExpressionWithParenthesis)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = e; 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("expression",8, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // statement_with_empty_line_and_comment ::= empty_line_and_comment 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = s; 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("statement_with_empty_line_and_comment",7, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // statement_with_empty_line_and_comment ::= statement 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = s; 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("statement_with_empty_line_and_comment",7, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // empty_line_and_comment ::= COMMENT 
            {
              Statement RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		java.lang.String c = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new CommentStatement(c); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("empty_line_and_comment",6, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // empty_line_and_comment ::= EMPTY_LINE 
            {
              Statement RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new EmptyLineStatement(); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("empty_line_and_comment",6, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // end_of_line_comment_opt ::= COMMENT 
            {
              java.lang.String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		java.lang.String c = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = c; 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("end_of_line_comment_opt",15, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // end_of_line_comment_opt ::= 
            {
              java.lang.String RESULT =null;
		 RESULT = null; 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("end_of_line_comment_opt",15, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // statement ::= FUNCTION IDENTIFIER LPAREN RPAREN statements 
            {
              Statement RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).right;
		java.lang.String i = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).value;
		int ssleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int ssright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Statements ss = (Statements)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new FunctionStatement(i, ss); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("statement",5, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-4)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // statement ::= FOR LPAREN variable_declaration EQ expression SEMICOLON expression SEMICOLON variable_declaration EQ expression RPAREN statements 
            {
              Statement RESULT =null;
		int i1left = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-10)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-10)).right;
		VariableDeclaration i1 = (VariableDeclaration)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-10)).value;
		int e1left = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-8)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-8)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-8)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-6)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-6)).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-6)).value;
		int i3left = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-4)).left;
		int i3right = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-4)).right;
		VariableDeclaration i3 = (VariableDeclaration)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-4)).value;
		int e3left = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).left;
		int e3right = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).right;
		Expression e3 = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).value;
		int ssleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int ssright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Statements ss = (Statements)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new ForStatement(i1, e1, e2, i3, e3, ss); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("statement",5, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-12)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // statement ::= WHILE LPAREN expression RPAREN statements 
            {
              Statement RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).value;
		int ssleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int ssright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Statements ss = (Statements)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new WhileStatement(e, ss); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("statement",5, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-4)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // statement ::= IF LPAREN expression RPAREN statements 
            {
              Statement RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).value;
		int s1left = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int s1right = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Statements s1 = (Statements)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new IfThenElseStatement(e, s1, null); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("statement",5, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-4)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // statement ::= IF LPAREN expression RPAREN statements ELSE statements 
            {
              Statement RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-4)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-4)).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-4)).value;
		int s1left = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).left;
		int s1right = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).right;
		Statements s1 = (Statements)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).value;
		int s2left = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int s2right = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Statements s2 = (Statements)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new IfThenElseStatement(e, s1, s2); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("statement",5, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-6)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // statement ::= IDENTIFIER LPAREN argument_list_opt RPAREN SEMICOLON end_of_line_comment_opt 
            {
              Statement RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-5)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-5)).right;
		java.lang.String i = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-5)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).right;
		ArgumentList a = (ArgumentList)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int oright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		java.lang.String o = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new MethodInvocationStatement(i, a, o); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("statement",5, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-5)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // statement ::= RETURN expression SEMICOLON end_of_line_comment_opt 
            {
              Statement RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int oright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		java.lang.String o = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new ReturnStatement(e, o); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("statement",5, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // statement ::= variable_declaration EQ expression SEMICOLON end_of_line_comment_opt 
            {
              Statement RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-4)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-4)).right;
		VariableDeclaration i = (VariableDeclaration)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-4)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int oright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		java.lang.String o = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new AssignmentStatement(i, e, o); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("statement",5, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-4)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // statement ::= TYPE variable_declaration_list SEMICOLON end_of_line_comment_opt 
            {
              Statement RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).right;
		java.lang.String t = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).right;
		java.util.List l = (java.util.List)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int oright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		java.lang.String o = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new DeclarationStatement(t, l, o); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("statement",5, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // statement ::= SEMICOLON end_of_line_comment_opt 
            {
              Statement RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int oright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		java.lang.String o = (java.lang.String)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new MethodInvocationStatement(o); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("statement",5, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // empty_statements_opt ::= empty_line_and_comment empty_statements_opt 
            {
              Statements RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).value;
		int ssleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int ssright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Statements ss = (Statements)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new Statements(s, ss); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("empty_statements_opt",4, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // empty_statements_opt ::= 
            {
              Statements RESULT =null;
		 RESULT = null; 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("empty_statements_opt",4, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // statements_with_braces ::= LBRACE statements_without_braces RBRACE empty_statements_opt 
            {
              Statements RESULT =null;
		int ssleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).left;
		int ssright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).right;
		Statements ss = (Statements)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Statements e = (Statements)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new Statements(null, ss, e); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("statements_with_braces",3, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-3)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // statements_without_braces ::= statement_with_empty_line_and_comment 
            {
              Statements RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new Statements(s); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("statements_without_braces",2, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // statements_without_braces ::= statements_with_braces statement_with_empty_line_and_comment 
            {
              Statements RESULT =null;
		int ssleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).left;
		int ssright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).right;
		Statements ss = (Statements)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new Statements(ss, s); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("statements_without_braces",2, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // statements_without_braces ::= statement_with_empty_line_and_comment statements_with_braces 
            {
              Statements RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).value;
		int ssleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int ssright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Statements ss = (Statements)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new Statements(s, ss); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("statements_without_braces",2, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // statements_without_braces ::= statement_with_empty_line_and_comment statements_without_braces 
            {
              Statements RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).value;
		int ssleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int ssright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Statements ss = (Statements)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new Statements(s, ss); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("statements_without_braces",2, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // statements ::= empty_statements_opt statement empty_statements_opt 
            {
              Statements RESULT =null;
		int o1left = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).left;
		int o1right = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).right;
		Statements o1 = (Statements)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).value;
		int o2left = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int o2right = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Statements o2 = (Statements)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new Statements(o1, s, o2); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("statements",1, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // statements ::= empty_statements_opt statements_with_braces empty_statements_opt 
            {
              Statements RESULT =null;
		int o1left = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).left;
		int o1right = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).right;
		Statements o1 = (Statements)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)).value;
		int ssleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).left;
		int ssright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).right;
		Statements ss = (Statements)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).value;
		int o2left = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int o2right = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Statements o2 = (Statements)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new Statements(o1, ss, o2); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("statements",1, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-2)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // parsed_tree ::= statements_without_braces 
            {
              ParsedTree RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()).right;
		Statements s = (Statements)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.peek()).value;
		 RESULT = new ParsedTree(s); 
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("parsed_tree",0, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          return CUP$GeneditsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= parsed_tree EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).right;
		ParsedTree start_val = (ParsedTree)((java_cup.runtime.Symbol) CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)).value;
		RESULT = start_val;
              CUP$GeneditsParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.elementAt(CUP$GeneditsParser$top-1)), ((java_cup.runtime.Symbol)CUP$GeneditsParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$GeneditsParser$parser.done_parsing();
          return CUP$GeneditsParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

