
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 15 11:19:33 EST 2018
//----------------------------------------------------

package com.imsweb.validation.translation.language.regex;

/** CUP generated class containing symbol constants. */
public class GeneditsRegexToken {
  /* terminals */
  public static final int PIPE = 22;
  public static final int PLUS = 18;
  public static final int RANGE = 10;
  public static final int LEFT_BRACE = 12;
  public static final int DIGIT = 9;
  public static final int CHAR = 4;
  public static final int STAR = 19;
  public static final int PERIOD = 23;
  public static final int LITERAL = 24;
  public static final int UPPER = 6;
  public static final int NO_BLANK = 3;
  public static final int LEFT_PAR = 16;
  public static final int COMMA = 21;
  public static final int LOWER = 7;
  public static final int EOF = 0;
  public static final int RIGHT_PAR = 17;
  public static final int LEFT_BRACKET = 14;
  public static final int error = 1;
  public static final int ESCAPE = 11;
  public static final int DASH = 20;
  public static final int ALPHA = 5;
  public static final int RIGHT_BRACE = 13;
  public static final int ALPHA_NUMERIC = 2;
  public static final int BLANK = 8;
  public static final int RIGHT_BRACKET = 15;
}

